### PR TITLE
Navigate webpage criteria

### PR DESCRIPTION
**Pull request by Z3MO1**

### CODE REVIEW

**Review by karina-talibzhanova — CHANGES_REQUESTED** [review]
rename products back to inventory, also navigation.feature is an empty file?

**Review by karina-talibzhanova — CHANGES_REQUESTED** [review]
split out the third scenario into 3 separate scenarios

**Review by karina-talibzhanova — APPROVED** [review]
i love it

**Review by KevinSimbana — APPROVED** [review]
Great stuff!

**Pull request merged**
